database: postgresql://postgres:31780@localhost:5432/web-tokens?sslmode=disable
base_url: "http://127.0.0.1"
base_port: "8989"
debug: true
logfile: debug.log
redis_address:

jwt_settings:
    private_key_path: "/home/arctur/workspace/src/github.com/auth-web-tokens/keys/private_key"
    public_key_path: "/home/arctur/workspace/src/github.com/auth-web-tokens/keys/public_key.pub"
    jwt_expiration_delta: 5